version: '2.4'

services:
  tx-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - >
        JAVA_OPTS=
        -Xmx512m
    mem_limit: 1G
    cpu_shares: 2048